In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel


X_train = np.load('initial_data/function_5/initial_inputs.npy')
Y_train = np.load('initial_data/function_5/initial_outputs.npy')
#[0.466721 0.335289 0.996526 0.964639]
X_train = np.append(X_train, [[0.466721,0.335289,0.996526,0.964639],[0.16951,0.763449,0.969853,0.995033],
                              [0.837681,0.951647,0.985609,0.992587],
                              [0.957219,0.992863,0.901772,0.949831]
], axis=0)
Y_train = np.append(Y_train,[1449.9884421183401,2104.7008579785,5315.03455866836,5547.522566794812])

print(X_train)
print(Y_train)

[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.53651774 0.65600038 0.36034155]
 [0.43834987 0.8043397  0.21024527 0.15129482]
 [0.70605083 0.53419196 0.26424335 0.48208755]
 [0.83647799 0.19360965 0.6638927  0.78564888]
 [0.68343225 0.11866264 0.82904591 0.56757661]
 [0.55362148 0.66734998 0.32380582 0.81486975]
 [0.35235627 0.32224153 0.11697937 0.47311252]
 [0.15378571 0.72938169 0.42259844 0.44307417]
 [0.46344227 0.63002451 0.10790646 0.9576439 ]
 [0.67749115 0.35850951 0.47959222 0.07288048]
 [0.58397341 0.14724265 0.34809746 0.42861465]
 [0.30688872 0.31687813 0.62263448 0.09539906]
 [0.51114177 0.817957   0.72871042 0.11235362]
 [0.43893338 0.77409176 0.37816709 0.93369621]
 [0.22418902 0.84648049 0.87948418 0.87851568]
 [0.72526172 0.47987049 0.08894684 0.75976022]
 [0.35548161 0.63961937 0.41761768 0.12260384]
 [0.11987923 0.86254031 0.64333133 0.84980383]
 [0.12688467 0.15342962 0.77016219 0.19051811]
 [0.466721   0.335289   0.996526   0.964639  ]
 [0.16951    

In [2]:
kernel = RBF(length_scale=np.ones(4)) + WhiteKernel(noise_level=1)
gp = GaussianProcessRegressor(kernel=kernel, alpha=1e-5, normalize_y=True)
gp.fit(X_train, Y_train.ravel())

C:\Code\RoughWork\Jupyter\venv\lib\site-packages\sklearn\gaussian_process\kernels.py:445: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


GaussianProcessRegressor(alpha=1e-05,
                         kernel=RBF(length_scale=[1, 1, 1, 1]) + WhiteKernel(noise_level=1),
                         normalize_y=True)

In [3]:
def ucb(X, gp, kappa=1.96):  # kappa can be adjusted based on your confidence level needs
    mean, std = gp.predict(X, return_std=True)
    return mean + kappa * std

# Generate random sample points
num_samples = 10000
test_points = np.random.uniform(0, 1, (num_samples, 4))

# Calculate UCB values for these points
ucb_values = ucb(test_points, gp)

# Find indices of the four highest UCB values
best_indices = np.argsort(-ucb_values)[:4]
best_hyperparameters = test_points[best_indices]

In [4]:
print("Best guesses for the hyperparameters based on UCB:")
for idx, params in enumerate(best_hyperparameters, start=1):
    print(f"Guess {idx}: {params}, UCB Score: {ucb_values[best_indices[idx-1]]}")


Best guesses for the hyperparameters based on UCB:
Guess 1: [0.99114255 0.77719472 0.94137197 0.99867221], UCB Score: 5848.812285638451
Guess 2: [0.97694784 0.81239664 0.89412581 0.96989971], UCB Score: 5571.057983237426
Guess 3: [0.90560206 0.90872085 0.89899193 0.9881644 ], UCB Score: 5499.412042450203
Guess 4: [0.98774408 0.91801432 0.90048079 0.88944835], UCB Score: 5441.642292277649
