In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel


X_train = np.load('initial_data/function_4/initial_inputs.npy')
Y_train = np.load('initial_data/function_4/initial_outputs.npy')
#[0.481151 0.434837 0.264911 0.436433]

X_train = np.append(X_train, [[0.481151 ,0.434837 ,0.264911 ,0.436433],
                              [0.396442,0.481382,0.401206,0.44157 ],
                              [0.413819,0.460116,0.366014,0.447818],
                              [0.387677,0.506365,0.408211,0.418344],
                              [0.412088,0.405466,0.405626,0.404682],
                              [0.458058,0.457745,0.452174,0.369015]], axis=0)
Y_train = np.append(Y_train, [-2.03426128331135,-1.31977049887937,-0.485344184,-1.30206004781646,0.5516510693090706,-1.12752945140463])
print(X_train)
print(Y_train)

[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]
 [0.25094624 0.03369313 0.14538002 0.49493242]
 [0.34696206 0.0062504  0.76056361 0.61302356]
 [0.12487118 0.12977019 0.38440048 0.2870761 ]
 [0.80130271 0.50023109 0.70664456 0.19510284]
 [0.24770826 0.06044543 0.04218635 0.44132425]
 [0.74670224 0.7570915  0.36935306 0.20656628]
 [0.40066503 0.07257425 0.88676825 0.24384229]
 [0.6260706  0.58675126 0.43880578 0.77885769]
 [0.95713529 0.59764438 0.76611385 0.77620991]
 [0.73281243 0.14524998 0.47681272 0.13336573]
 [0.65511548 0.07239183 0.68715175 0.08151656]
 [0.21973443 0.83203134 0.48286416 0.08256923]
 [0.48859419 0.2119651  0.93917791 0.37619173]
 [0.16713049 0.87655456 0.21723954 0.95980098]
 [0.21691119 0.16608583 0.24137226 0.77006248]
 [0.38748784 0.80453226 0.75179548 0.72382744]
 [0.98562189 0.66693268 0.15678328 0.8565348 ]
 [0.03782483 0.66485335 0.16198218 0.25392378]
 [0.68348638 0.9027701  0.33541983 0.99948256]
 [0.17034731 

In [2]:
kernel = RBF(length_scale=np.ones(4)) + WhiteKernel(noise_level=1)
gp = GaussianProcessRegressor(kernel=kernel, alpha=1e-5, normalize_y=True)
gp.fit(X_train, Y_train.ravel())

GaussianProcessRegressor(alpha=1e-05,
                         kernel=RBF(length_scale=[1, 1, 1, 1]) + WhiteKernel(noise_level=1),
                         normalize_y=True)

In [3]:
def ucb(X, gp, kappa=1.96):  # kappa can be adjusted based on your confidence level needs
    mean, std = gp.predict(X, return_std=True)
    return mean + kappa * std

# Generate random sample points
num_samples = 10000
test_points = np.random.uniform(0, 1, (num_samples, 4))

# Calculate UCB values for these points
ucb_values = ucb(test_points, gp)

# Find indices of the four highest UCB values
best_indices = np.argsort(-ucb_values)[:4]
best_hyperparameters = test_points[best_indices]

In [4]:
print("Best guesses for the hyperparameters based on UCB:")
for idx, params in enumerate(best_hyperparameters, start=1):
    print(f"Guess {idx}: {params}, UCB Score: {ucb_values[best_indices[idx-1]]}")


Best guesses for the hyperparameters based on UCB:
Guess 1: [0.44052378 0.44846243 0.37826152 0.4684904 ], UCB Score: 0.4357539450961869
Guess 2: [0.34362826 0.39535963 0.46371348 0.41155731], UCB Score: 0.22704099919736032
Guess 3: [0.35459964 0.34874928 0.39330769 0.40027649], UCB Score: 0.16292936888968335
Guess 4: [0.38031853 0.40059441 0.31346662 0.39903039], UCB Score: 0.05352198332267366
